package akin.city_card.admin.model;

public enum ActionType {

    // 🔐 GİRİŞ / GÜVENLİK
    LOGIN,
    LOGOUT,
    RESET_PASSWORD,
    CHANGE_PASSWORD,
    VERIFICATION_SMS_SENT,
    PHONE_VERIFIED,
    EMAIL_VERIFIED,
    ACCEPT_CONTRACT,
    REJECT_CONTRACT,
    VIEW_CONTRACTS,

    // Session Management Actions
    TERMINATE_SESSION,
    TERMINATE_ALL_SESSIONS,
    VIEW_ACTIVE_SESSIONS,

    // 👤 KULLANICI HESABI
    SIGN_UP,
    COLLECTIVE_SIGN_UP,
    UPDATE_PROFILE,
    DELETE_USER,
    DEACTIVATE_ACCOUNT,
    ACTIVATE_ACCOUNT,
    UPLOAD_PROFILE_PHOTO,

    // 🛡️ YETKİLENDİRME / ADMIN
    APPROVE_ADMIN,
    BLOCK_USER,
    UNBLOCK_USER,
    PROMOTE_TO_ADMIN,
    DEMOTE_TO_USER,

    // 🚌 KART İŞLEMLERİ
    ADD_BUS_CARD,
    DELETE_BUS_CARD,
    UPDATE_BUS_CARD_ALIAS,
    FAVORITE_CARD_ADDED,
    FAVORITE_CARD_REMOVED,
    SET_LOW_BALANCE_ALERT,
    REMOVE_LOW_BALANCE_ALERT,
    BUS_CARD_TOP_UP,
    BUS_CARD_TRANSFER,

    // 🚏 ROTA VE GÜZERGAH
    FAVORITE_ROUTE_ADDED,
    FAVORITE_ROUTE_REMOVED,
    VIEW_ROUTE_DETAILS,

    // 🧭 KONUM / GEO
    LOCATION_UPDATED,
    ADD_GEO_ALERT,
    DELETE_GEO_ALERT,
    TRIGGERED_GEO_ALERT,

    // 👛 CÜZDAN VE ÖDEME
    CREATE_WALLET,
    DELETE_WALLET,
    WALLET_TOP_UP,
    AUTO_TOP_UP_ENABLED,
    AUTO_TOP_UP_DISABLED,
    AUTO_TOP_UP_CONFIG_ADDED,
    AUTO_TOP_UP_CONFIG_REMOVED,
    WALLET_TRANSFER,

    // 📢 BİLDİRİM VE TERCİHLER
    UPDATE_NOTIFICATION_PREFERENCES,
    NOTIFICATION_RECEIVED,
    NOTIFICATION_READ,

    // 📰 HABERLER
    VIEWED_NEWS,
    LIKED_NEWS,
    UNLIKED_NEWS,

    // 🔍 ARAMA VE GEÇMİŞ
    SEARCH_PERFORMED,
    SEARCH_HISTORY_CLEARED,

    // 🧪 DOĞRULAMA KODLARI
    SEND_PHONE_VERIFICATION_CODE,
    RESEND_PHONE_VERIFICATION_CODE,
    VERIFY_PHONE_CODE,

    // ⚙️ SİSTEM / GENEL
    SYSTEM_MAINTENANCE_START,
    SYSTEM_MAINTENANCE_END,
    SYSTEM_ALERT_ACKNOWLEDGED,

    // 📊 RAPOR VE ANALİZ
    EXPORT_USER_DATA,
    EXPORT_WALLET_HISTORY,
    FREEZE_ACCOUNT,
    UNFREEZE_ACCOUNT,
    ADMIN_TERMINATE_SESSION,
    USER_REGISTER,
    USER_PHONE_VERIFIED,
    USER_PROFILE_VIEWED,
    USER_PROFILE_UPDATED,
    BULK_USER_CREATED,
    USER_PROFILE_PHOTO_UPDATED,
    PASSWORD_RESET_CODE_SENT,
    USER_PASSWORD_RESET,
    CREATE_ADMIN, UPDATE_ADMIN, DELETE_ADMIN, UPDATE_ADMIN_STATUS, LOGIN_FAILED, MULTIPLE_LOGIN_ATTEMPTS, DEVICE_BANNED, IP_BANNED, PASSWORD_RESET_SUSPICIOUS, ACCOUNT_LOCKED, SESSION_TERMINATED, ADMIN_LIST_USERS, ADMIN_SEARCH_USERS, ADMIN_BULK_UPDATE_USER_STATUS, ADMIN_BULK_DELETE_USERS, ADMIN_GET_USER_BY_ID, ADMIN_GET_USER_DEVICE_INFO, ADMIN_UPDATE_PHONE_VERIFICATION, ADMIN_UPDATE_EMAIL_VERIFICATION, ADMIN_ASSIGN_ROLES, ADMIN_REMOVE_ROLES, ADMIN_BULK_ASSIGN_ROLES, ADMIN_RESET_PASSWORD, EXPORT_LOGIN_HISTORY
}
