package akin.city_card.security.entity;

import lombok.RequiredArgsConstructor;
import org.springframework.security.core.GrantedAuthority;

@RequiredArgsConstructor
public enum Role implements GrantedAuthority {
    ADMIN("ADMIN"),
    SUPERADMIN("SUPERADMIN"),
    USER("USER"),
    DRIVER("DRIVER"),
    MODERATOR("MODERATOR"),

    USER_CREATE("USER_CREATE"),
    USER_READ("USER_READ"),
    USER_UPDATE("USER_UPDATE"),
    USER_DELETE("USER_DELETE"),

    // STATION yönetimi
    STATION_CREATE("STATION_CREATE"),
    STATION_READ("STATION_READ"),
    STATION_UPDATE("STATION_UPDATE"),
    STATION_DELETE("STATION_DELETE"),

    // ROUTE
    ROUTE_CREATE("ROUTE_CREATE"),
    ROUTE_READ("ROUTE_READ"),
    ROUTE_UPDATE("ROUTE_UPDATE"),
    ROUTE_DELETE("ROUTE_DELETE"),

    // REPORT
    REPORT_CREATE("REPORT_CREATE"),
    REPORT_READ("REPORT_READ"),
    REPORT_UPDATE("REPORT_UPDATE"),
    REPORT_DELETE("REPORT_DELETE"),

    // PAYMENT
    PAYMENT_CREATE("PAYMENT_CREATE"),
    PAYMENT_READ("PAYMENT_READ"),
    PAYMENT_UPDATE("PAYMENT_UPDATE"),
    PAYMENT_DELETE("PAYMENT_DELETE"),

    // POINT
    POINT_CREATE("POINT_CREATE"),
    POINT_READ("POINT_READ"),
    POINT_UPDATE("POINT_UPDATE"),
    POINT_DELETE("POINT_DELETE"),

    // NEWS
    NEWS_CREATE("NEWS_CREATE"),
    NEWS_READ("NEWS_READ"),
    NEWS_UPDATE("NEWS_UPDATE"),
    NEWS_DELETE("NEWS_DELETE"),

    // HEALTH
    HEALTH_CREATE("HEALTH_CREATE"),
    HEALTH_READ("HEALTH_READ"),
    HEALTH_UPDATE("HEALTH_UPDATE"),
    HEALTH_DELETE("HEALTH_DELETE"),

    // GEOALERT
    GEOALERT_CREATE("GEOALERT_CREATE"),
    GEOALERT_READ("GEOALERT_READ"),
    GEOALERT_UPDATE("GEOALERT_UPDATE"),
    GEOALERT_DELETE("GEOALERT_DELETE"),

    // FEEDBACK
    FEEDBACK_CREATE("FEEDBACK_CREATE"),
    FEEDBACK_READ("FEEDBACK_READ"),
    FEEDBACK_UPDATE("FEEDBACK_UPDATE"),
    FEEDBACK_DELETE("FEEDBACK_DELETE"),

    // DRIVER
    DRIVER_CREATE("DRIVER_CREATE"),
    DRIVER_READ("DRIVER_READ"),
    DRIVER_UPDATE("DRIVER_UPDATE"),
    DRIVER_DELETE("DRIVER_DELETE"),

    // CONTRACT
    CONTRACT_CREATE("CONTRACT_CREATE"),
    CONTRACT_READ("CONTRACT_READ"),
    CONTRACT_UPDATE("CONTRACT_UPDATE"),
    CONTRACT_DELETE("CONTRACT_DELETE"),

    // BUS
    BUS_CREATE("BUS_CREATE"),
    BUS_READ("BUS_READ"),
    BUS_UPDATE("BUS_UPDATE"),
    BUS_DELETE("BUS_DELETE"),

    // BUSCARD
    BUSCARD_CREATE("BUSCARD_CREATE"),
    BUSCARD_READ("BUSCARD_READ"),
    BUSCARD_UPDATE("BUSCARD_UPDATE"),
    BUSCARD_DELETE("BUSCARD_DELETE"),

    // AUTOTOPUP
    AUTOTOPUP_CREATE("AUTOTOPUP_CREATE"),
    AUTOTOPUP_READ("AUTOTOPUP_READ"),
    AUTOTOPUP_UPDATE("AUTOTOPUP_UPDATE"),
    AUTOTOPUP_DELETE("AUTOTOPUP_DELETE"),

    // Tam erişim (superadmin veya sistem admin için)
    SYSTEM_ADMIN("SYSTEM_ADMIN");

    private final String role;
    @Override
    public String getAuthority() {
        return role;
    }
}
