package akin.city_card.security.entity;

public enum SecurityEventType {
    // Authentication events
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    TOKEN_REFRESH,
    TOKEN_EXPIRED,
    TOKEN_REVOKED,
    
    // Account management
    ACCOUNT_CREATED,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    ACCOUNT_DELETED,
    PASSWORD_CHANGE,
    PASSWORD_RESET_REQUEST,
    PASSWORD_RESET_COMPLETE,
    
    // Authorization events
    PERMISSION_DENIED,
    ROLE_CHANGED,
    PRIVILEGE_ESCALATION_ATTEMPT,
    
    // Security violations
    RATE_LIMIT_EXCEEDED,
    SUSPICIOUS_ACTIVITY,
    BRUTE_FORCE_ATTEMPT,
    SQL_INJECTION_ATTEMPT,
    XSS_ATTEMPT,
    CSRF_ATTEMPT,
    
    // Administrative actions
    ADMIN_ACTION,
    ADMIN_LOGIN,
    SUPERADMIN_ACTION,
    SUPERADMIN_LOGIN,
    
    // System events
    SYSTEM_START,
    SYSTEM_SHUTDOWN,
    CONFIG_CHANGE,
    
    // Data access
    SENSITIVE_DATA_ACCESS,
    DATA_EXPORT,
    DATA_MODIFICATION,
    
    // IP and Device
    NEW_DEVICE_LOGIN,
    UNRECOGNIZED_LOCATION,
    IP_BLACKLISTED,
    
    // API Security
    API_KEY_CREATED,
    API_KEY_REVOKED,
    NEW_DEVICE_VERIFIED, SESSION_REVOKED, VERIFICATION_CODE_RESENT, UNFREEZE_FAILED, ACCOUNT_UNFROZEN, TOKEN_ISSUED, VERIFICATION_CODE_SENT, API_ABUSE_DETECTED
}
